version: "3"

services:
  postgres:
    container_name: deploy-tool-postgres-db
    build:
      context: .docker
      dockerfile: postgres.dockerfile
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/postgres/logs:/logs
    env_file:
      - ./.docker/postgres.env
    ports:
      - "5433:5432"
